### ISSUE TITLE
[Bug]: Resource identified by [PanelSystem\Pet\Resources\UserResource] is not registered.

### ISSUE THREAD

**Issue by WillieOng-HK** [rhiannonjourney/filament-resource-picker#3]
### What happened?

I got an error message `Resource identified by [PanelSystem\Pet\Resources\UserResource] is not registered.`
I already register this plugin in the panel. 
```
Forms\Components\Section::make('Basic Information')
  ->schema([
     // ...
      ResourcePicker::make('component_id')
          ->resource(UserResource::class),
  ]);
```

### How to reproduce the bug

After added these code, and click the create button.

### Package Version

1.0.0

### PHP Version

PHP 8.2.0

### Laravel Version

10.0.0

**Comment by rhiannonjourney** [comment]
@WillieOng-HK Thanks for the feedback. Are you trying to use the `ResourcePicker` inside of a panel or in a form built using the Form Builder as a standalone package? Also, is your `UserResource` inside of the same panel that your code above lives?


I'll dig into this more sometime in the next couple of days when I have a chance.

**Comment by WillieOng-HK** [comment]
I think it is because the `$panel->getResources()` only get the resource which registered in config/app.php, not inside the PanelProvider > Plugin > resource.

**Comment by WillieOng-HK** [comment]
I got some hints after some investigate, will you consider using `\Filament\Facades\Filament::getResources()` inside boot method, instead of `$panel->getResources()` inside register method? because `Filament::getResources()` can get all resources across all plugins registered.

**Comment by rhiannonjourney** [comment]
Thanks for investigating. I did some digging also and the `getReources()` method on the `Filament` facade [only gets the resources registered for the current panel](https://github.com/filamentphp/filament/blob/f3dfe3d2c35686b27ed8afeca6680116d55849ef/packages/panels/src/FilamentManager.php#L310). 

What I did instead was to add the ability to register additional resources when you add the plugin to your panel. In your PetPanelProvider instead of 

```PHP
public function panel(Panel $panel): Panel
{
    return $panel
        ...
        ->plugins([
            FilamentResourcePickerPlugin::make()
        ]);
}
```

you would do

```PHP
public function panel(Panel $panel): Panel
{
    return $panel
        ...
        ->plugins([
            FilamentResourcePickerPlugin::make()
                ->registerAdditionalResources([
                    UserResource::class
                ])
        ]);
}
```

Would you mind trying out the 'bug/register-additional-resources' branch and make sure it works for you? If you have other ideas to accomplish this I'm also open to them/

**Comment by rhiannonjourney** [comment]
Closing this as the latest 1.0.2 version fixes this issue by adding a `registerAdditionResources()` method when configuring the plugin on your panel. Using this, you can register any extra resources from other panels, making them available for use in the current panel.
